apiVersion: apps/v1
kind: Deployment
metadata:
  name: cst-multimoedas-backend-homolog
  namespace: cst-multimoedas-homolog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cst-multimoedas-backend-homolog
  template:
    metadata:
      labels:
        app: cst-multimoedas-backend-homolog
    spec:
      containers:
        - name: cst-multimoedas-backend-homolog-container
          image: ghcr.io/oondemand/cst-multimoedas-backend:${IMAGE_TAG}-homolog
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "256Mi"
              cpu: "0.2"
          env:
            - name: NODE_ENV
              value: "${NODE_ENV}"
            - name: SERVICE_NAME
              value: "${SERVICE_NAME}"
            - name: PORT
              value: "${PORT}"
            - name: DB_SERVER
              value: "${DB_SERVER}"
            - name: DB_USER
              value: "${DB_USER}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_NAME
              value: "${DB_NAME}"
            - name: DB_AUTH_SOURCE
              value: "${DB_AUTH_SOURCE}"
            - name: DB_REPLICA_SET
              value: "${DB_REPLICA_SET}"
            - name: DB_TSL
              value: "${DB_TSL}"
            - name: API_OMIE
              value: "${API_OMIE}"
            - name: JWT_SECRET
              value: "${JWT_SECRET}"
            - name: BASE_URL_CST
              value: "${BASE_URL_CST}"
            - name: BASE_URL_APP_PUBLISHER
              value: "${BASE_URL_APP_PUBLISHER}"
            - name: MEUS_APPS_BACKEND_URL
              value: "${MEUS_APPS_BACKEND_URL}"
